### PR TITLE
Replace histogram with add.at and refactor jit compilation

### PR DESCRIPTION
**Pull request by marcelo-alvarez**
See comments below for summary.

### CODE REVIEW

**Comment by marcelo-alvarez** [comment]
@1cosmologist this is still being tested, but please feel free to review for style, thanks.

**Comment by marcelo-alvarez** [comment]
Reverted to only removing astype calls from `cosmology.py` and `kernel_lib.py`.

**Comment by marcelo-alvarez** [comment]
@1cosmologist this is now ready for review and merging. Significant changes:
1. logging now includes MPI rank information when reporting the grid setup
2. the kernel weights in the jnp.histogram method are cast to float64
I have tested this with nside=2048 and it now produces an artefact-free map on 4 Perlmutter nodes with 
```
export LPT_DISPLACEMENTS_PATH=/dvs_ro/cfs/cdirs/m3058/malvarez/websky-displacements/
export XLA_PYTHON_CLIENT_ALLOCATOR=platform
srun -n 16--gpus-per-task=1 python lptmap/py/lptmap/lightcone.py --grid-nside 6144 --map-nside 2048
```
Please merge if it looks good, thanks.

**Comment by 1cosmologist** [comment]
@marcelo-alvarez Any particular reason to not jit the whole `grid2map` function, instead of parts in it? The type module and setting jax types somewhere in `jax_backend` has also been removed?

**Comment by marcelo-alvarez** [comment]
@1cosmologist tests indicated jit compiling only the individual functions reduced the memory footprint significantly but, I was not very systematic. If you find jit compiling grid2map works for Nside=2048 without increasing peak_per_cell_memory above its current value of 75, then I'm fine with you committing changes to revert back to jit compiling the whole function.

I removed the jax types since that was not necessary. I suggest we address that separately from this.

**Comment by 1cosmologist** [comment]
I was suggested to jit compile as many lines of code as possible to improve code optimization by the XLA compiler. It makes sense that this would also lead to higher memory overhead as jax would try to optimize allocation and deallocation for speed. The new `.at.add` way of doing the binning has given a significant speed boost. So, I don't necessarily think that we need big chunks of jit compiled code as the benefits are currently debatable.

**Comment by 1cosmologist** [comment]
Do we require the `float32` type enforcement in `liblightcone`? I have also removed `trans_vec`, `Dgrid_in_Mpc` from the arguments of `euclid_i` function. They we not getting used anyway.

**Comment by marcelo-alvarez** [comment]
I don't think we need the float32 casting for any jax numpy array and that it would be ok to remove.

**Comment by 1cosmologist** [comment]
Removed all `jnp.float32` type casting for jax arrays. Validated on full 6144 grid with map nside set to 2048. 
image
image

**Comment by 1cosmologist** [comment]
Opened a new issue #13 for 32 bits/64 bits switching for `NSIDE>8192` case.

**Pull request merged**
